name: Build Dataset

on:
  workflow_dispatch:
    inputs:
      year:        { description: "Season year", required: true, default: "2025" }
      drive_weeks: { description: "Weeks for drives (e.g. 1-6,10)", required: false, default: "6" }

permissions: { contents: write }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt || pip install pandas pyarrow requests
      - name: Build local dataset
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          YEAR: ${{ github.event.inputs.year }}
          DRIVE_WEEKS: ${{ github.event.inputs.drive_weeks }}
        run: python .github/runner/build_dataset.py
      - name: Commit data
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name  "github-actions[bot]"
          git add data/
          git commit -m "Update dataset ${{ github.event.inputs.year }}" || echo "No changes"
          git push