- name: Build week predictions & publish JSON
  env:
    CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
    YEAR:  ${{ github.event.inputs.year }}
    WEEK:  ${{ github.event.inputs.week }}
    SCOPE: ${{ github.event.inputs.scope }}
    MODE:  ${{ github.event.inputs.mode }}
  run: |
    python .github/runner/mini_loader.py
    python .github/runner/weekly.py