name: Weekly Runner

on:
  workflow_dispatch:
    inputs:
      year:  { description: "Season year (e.g. 2025)", required: true, default: "2025" }
      week:  { description: "Week number",            required: true, default: "6" }
      scope: { description: "Scope (all | top25 | top10)", required: true, default: "all" }
      mode:  { description: "Mode (FAST | FULL)",     required: true, default: "FULL" }

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt || pip install pandas pyarrow requests

      - name: Build week predictions & publish JSON
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          YEAR:  ${{ github.event.inputs.year }}
          WEEK:  ${{ github.event.inputs.week }}
          SCOPE: ${{ github.event.inputs.scope }}
          MODE:  ${{ github.event.inputs.mode }}
        run: |
          python .github/runner/mini_loader.py
          python .github/runner/weekly.py
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30   # ← give the loader plenty of runway
    steps:
      ...
      - name: Commit JSON/data to repo (for Pages)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/*.json week_preds.csv data/
          git commit -m "Auto update week ${{ github.event.inputs.week }} (${{ github.event.inputs.year }})" || echo "No changes to commit"
          git push

      - name: Peek cache + outputs
        run: |
          echo "== cache listing ==" && ls -lh data/weeks/${{ github.event.inputs.year }}/ || true
          echo "== games cache size ==" && wc -c data/weeks/${{ github.event.inputs.year }}/week_${{ github.event.inputs.week }}.games.json || true
          echo "== rankings cache head ==" && head -n 20 data/weeks/${{ github.event.inputs.year }}/week_${{ github.event.inputs.week }}.rankings.json || true
          echo "== docs listing ==" && ls -lh docs || true
          echo "== week_preds head ==" && head -n 40 docs/week_preds.json || true

      - name: Sanity peek
        run: |
          echo "== docs ==" && ls -lh docs || true
          echo "== size week_preds.json ==" && wc -c docs/week_preds.json || true
          echo "== head ==" && head -n 40 docs/week_preds.json || true