name: CFB Model — Weekly Runner

on:
  workflow_dispatch:
    inputs:
      year:
        description: "Season year"
        required: true
        default: "2025"
      week:
        description: "Week number"
        required: true
        default: "6"
      scope:
        description: "Scope of teams (all, top25, top10)"
        required: true
        default: "top25"
      mode:
        description: "Run mode (FULL or FAST)"
        required: true
        default: "FULL"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install pandas httpx

      - name: Build Week predictions & publish JSON
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          YEAR: ${{ github.event.inputs.year }}
          WEEK: ${{ github.event.inputs.week }}
          SCOPE: ${{ github.event.inputs.scope }}
          MODE: ${{ github.event.inputs.mode }}
        run: |
          python .github/runner/weekly.py

   - name: Commit JSON to docs (for Pages)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/week_preds.json
          git commit -m "Publish week_preds.json" || echo "No changes"
          git push

      - name: Show JSON summary   # 👈 optional sanity check
        run: |
          echo "Rows in docs/week_preds.json:"
          cat docs/week_preds.json | wc -c || true
          cat docs/week_preds.json | head -n 20 || true

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: week_preds
          path: week_preds.csv